//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalletCheck {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringsLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PalletCheck.StringsLocalization", typeof(StringsLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AngleThresholdDegree.
        /// </summary>
        internal static string AngleThresholdDegree {
            get {
                return ResourceManager.GetString("AngleThresholdDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoStartCapturing.
        /// </summary>
        internal static string AutoStartCapturing {
            get {
                return ResourceManager.GetString("AutoStartCapturing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlockHeight1.
        /// </summary>
        internal static string BlockHeight1 {
            get {
                return ResourceManager.GetString("BlockHeight1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlockHeight2.
        /// </summary>
        internal static string BlockHeight2 {
            get {
                return ResourceManager.GetString("BlockHeight2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlockHeight3.
        /// </summary>
        internal static string BlockHeight3 {
            get {
                return ResourceManager.GetString("BlockHeight3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlockMissingMaximum.
        /// </summary>
        internal static string BlockMissingMaximum {
            get {
                return ResourceManager.GetString("BlockMissingMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlockProtrudingfromPalletMaximum.
        /// </summary>
        internal static string BlockProtrudingfromPalletMaximum {
            get {
                return ResourceManager.GetString("BlockProtrudingfromPalletMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlockWidth1.
        /// </summary>
        internal static string BlockWidth1 {
            get {
                return ResourceManager.GetString("BlockWidth1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlockWidth2.
        /// </summary>
        internal static string BlockWidth2 {
            get {
                return ResourceManager.GetString("BlockWidth2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlockWidth3.
        /// </summary>
        internal static string BlockWidth3 {
            get {
                return ResourceManager.GetString("BlockWidth3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoardCenterCrackExclusionZonePercentage.
        /// </summary>
        internal static string BoardCenterCrackExclusionZonePercentage {
            get {
                return ResourceManager.GetString("BoardCenterCrackExclusionZonePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        internal static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CameraCount.
        /// </summary>
        internal static string CameraCount {
            get {
                return ResourceManager.GetString("CameraCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CameraEnabled.
        /// </summary>
        internal static string CameraEnabled {
            get {
                return ResourceManager.GetString("CameraEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrackTrackerBlockSize.
        /// </summary>
        internal static string CrackTrackerBlockSize {
            get {
                return ResourceManager.GetString("CrackTrackerBlockSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrackTrackerMinDelta.
        /// </summary>
        internal static string CrackTrackerMinDelta {
            get {
                return ResourceManager.GetString("CrackTrackerMinDelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrackTrackerMinPct.
        /// </summary>
        internal static string CrackTrackerMinPct {
            get {
                return ResourceManager.GetString("CrackTrackerMinPct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndCropX.
        /// </summary>
        internal static string EndCropX {
            get {
                return ResourceManager.GetString("EndCropX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndCropY.
        /// </summary>
        internal static string EndCropY {
            get {
                return ResourceManager.GetString("EndCropY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndX0.
        /// </summary>
        internal static string EndX0 {
            get {
                return ResourceManager.GetString("EndX0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndX1.
        /// </summary>
        internal static string EndX1 {
            get {
                return ResourceManager.GetString("EndX1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndX2.
        /// </summary>
        internal static string EndX2 {
            get {
                return ResourceManager.GetString("EndX2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForkClearancePercentageMinimum.
        /// </summary>
        internal static string ForkClearancePercentageMinimum {
            get {
                return ResourceManager.GetString("ForkClearancePercentageMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1BoardMinimumWidthAcrossLength.
        /// </summary>
        internal static string H1BoardMinimumWidthAcrossLength {
            get {
                return ResourceManager.GetString("H1BoardMinimumWidthAcrossLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1MissingChunkMinimumLength.
        /// </summary>
        internal static string H1MissingChunkMinimumLength {
            get {
                return ResourceManager.GetString("H1MissingChunkMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1MissingChunkMinimumWidth.
        /// </summary>
        internal static string H1MissingChunkMinimumWidth {
            get {
                return ResourceManager.GetString("H1MissingChunkMinimumWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2BoardMinimumWidthAcrossLength.
        /// </summary>
        internal static string H2BoardMinimumWidthAcrossLength {
            get {
                return ResourceManager.GetString("H2BoardMinimumWidthAcrossLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2MissingChunkMinimumLength.
        /// </summary>
        internal static string H2MissingChunkMinimumLength {
            get {
                return ResourceManager.GetString("H2MissingChunkMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2MissingChunkMinimumWidth.
        /// </summary>
        internal static string H2MissingChunkMinimumWidth {
            get {
                return ResourceManager.GetString("H2MissingChunkMinimumWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H9BoardMinimumWidthAcrossLength{0}.
        /// </summary>
        internal static string H9BoardMinimumWidthAcrossLength {
            get {
                return ResourceManager.GetString("H9BoardMinimumWidthAcrossLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HBoardEdgeCrackExclusionZonePercentage.
        /// </summary>
        internal static string HBoardEdgeCrackExclusionZonePercentage {
            get {
                return ResourceManager.GetString("HBoardEdgeCrackExclusionZonePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HBoardLength{0}_in.
        /// </summary>
        internal static string HBoardLength_in {
            get {
                return ResourceManager.GetString("HBoardLength_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HBoardWidth_in.
        /// </summary>
        internal static string HBoardWidth_in {
            get {
                return ResourceManager.GetString("HBoardWidth_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H{0}MaxAllowedMissingWood{1}.
        /// </summary>
        internal static string HXMaxAllowedMissingWood {
            get {
                return ResourceManager.GetString("HXMaxAllowedMissingWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H{0}MissingChunkMaximumLength{1}.
        /// </summary>
        internal static string HXMissingChunkMaximumLength {
            get {
                return ResourceManager.GetString("HXMissingChunkMaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H{0}MissingChunkMaximumWidth{1}.
        /// </summary>
        internal static string HXMissingChunkMaximumWidth {
            get {
                return ResourceManager.GetString("HXMissingChunkMaximumWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinearSupportBoardMissingWoodPercentageMaximum.
        /// </summary>
        internal static string LinearSupportBoardMissingWoodPercentageMaximum {
            get {
                return ResourceManager.GetString("LinearSupportBoardMissingWoodPercentageMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxExposedNailHeight_mm.
        /// </summary>
        internal static string MaxExposedNailHeight_mm {
            get {
                return ResourceManager.GetString("MaxExposedNailHeight_mm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinBoardLength.
        /// </summary>
        internal static string MinBoardLength {
            get {
                return ResourceManager.GetString("MinBoardLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMPerPixelX.
        /// </summary>
        internal static string MMPerPixelX {
            get {
                return ResourceManager.GetString("MMPerPixelX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMPerPixelY.
        /// </summary>
        internal static string MMPerPixelY {
            get {
                return ResourceManager.GetString("MMPerPixelY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMPerPixelZ.
        /// </summary>
        internal static string MMPerPixelZ {
            get {
                return ResourceManager.GetString("MMPerPixelZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RN_NailConfirmationsRequired.
        /// </summary>
        internal static string NailConfirmationsRequired {
            get {
                return ResourceManager.GetString("NailConfirmationsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RN_NailConfirmHeadInnerRadius.
        /// </summary>
        internal static string NailConfirmHeadInnerRadius {
            get {
                return ResourceManager.GetString("NailConfirmHeadInnerRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RN_NailConfirmHeadOuterRadius.
        /// </summary>
        internal static string NailConfirmHeadOuterRadius {
            get {
                return ResourceManager.GetString("NailConfirmHeadOuterRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RN_NailConfirmSurfaceRadius.
        /// </summary>
        internal static string NailConfirmSurfaceRadius {
            get {
                return ResourceManager.GetString("NailConfirmSurfaceRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RN_NailNeighborSamplePoints.
        /// </summary>
        internal static string NailNeighborSamplePoints {
            get {
                return ResourceManager.GetString("NailNeighborSamplePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RN_NailNeighborSampleRadius.
        /// </summary>
        internal static string NailNeighborSampleRadius {
            get {
                return ResourceManager.GetString("NailNeighborSampleRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NailProtrudingfromSideofPalletMaximum.
        /// </summary>
        internal static string NailProtrudingfromSideofPalletMaximum {
            get {
                return ResourceManager.GetString("NailProtrudingfromSideofPalletMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OffsetZ0.
        /// </summary>
        internal static string OffsetZ0 {
            get {
                return ResourceManager.GetString("OffsetZ0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OffsetZ1.
        /// </summary>
        internal static string OffsetZ1 {
            get {
                return ResourceManager.GetString("OffsetZ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OffsetZ2.
        /// </summary>
        internal static string OffsetZ2 {
            get {
                return ResourceManager.GetString("OffsetZ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RaisedBoardMaximumHeight.
        /// </summary>
        internal static string RaisedBoardMaximumHeight {
            get {
                return ResourceManager.GetString("RaisedBoardMaximumHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RaisedBoardMaximumWidth.
        /// </summary>
        internal static string RaisedBoardMaximumWidth {
            get {
                return ResourceManager.GetString("RaisedBoardMaximumWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RawCaptureROIBottom_px.
        /// </summary>
        internal static string RawCaptureROIBottom_px {
            get {
                return ResourceManager.GetString("RawCaptureROIBottom_px", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RawCaptureROILeft_px.
        /// </summary>
        internal static string RawCaptureROILeft_px {
            get {
                return ResourceManager.GetString("RawCaptureROILeft_px", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RawCaptureROIMaxZ_px.
        /// </summary>
        internal static string RawCaptureROIMaxZ_px {
            get {
                return ResourceManager.GetString("RawCaptureROIMaxZ_px", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RawCaptureROIMinZ_px.
        /// </summary>
        internal static string RawCaptureROIMinZ_px {
            get {
                return ResourceManager.GetString("RawCaptureROIMinZ_px", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RawCaptureROIRight_px.
        /// </summary>
        internal static string RawCaptureROIRight_px {
            get {
                return ResourceManager.GetString("RawCaptureROIRight_px", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RawCaptureROITop_px.
        /// </summary>
        internal static string RawCaptureROITop_px {
            get {
                return ResourceManager.GetString("RawCaptureROITop_px", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate90.
        /// </summary>
        internal static string Rotate90 {
            get {
                return ResourceManager.GetString("Rotate90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SideLength.
        /// </summary>
        internal static string SideLength {
            get {
                return ResourceManager.GetString("SideLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SplitDL_ScaleY_Leading.
        /// </summary>
        internal static string SplitDL_ScaleY_Leading {
            get {
                return ResourceManager.GetString("SplitDL_ScaleY_Leading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SplitDL_ScaleY_Trailing.
        /// </summary>
        internal static string SplitDL_ScaleY_Trailing {
            get {
                return ResourceManager.GetString("SplitDL_ScaleY_Trailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartCropX.
        /// </summary>
        internal static string StartCropX {
            get {
                return ResourceManager.GetString("StartCropX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartCropY.
        /// </summary>
        internal static string StartCropY {
            get {
                return ResourceManager.GetString("StartCropY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartX0.
        /// </summary>
        internal static string StartX0 {
            get {
                return ResourceManager.GetString("StartX0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartX1.
        /// </summary>
        internal static string StartX1 {
            get {
                return ResourceManager.GetString("StartX1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartX2.
        /// </summary>
        internal static string StartX2 {
            get {
                return ResourceManager.GetString("StartX2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        internal static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TopH{0}BoardWidth_in.
        /// </summary>
        internal static string TopHXBoardWidth_in {
            get {
                return ResourceManager.GetString("TopHXBoardWidth_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallet Check POC.
        /// </summary>
        internal static string UI_Title {
            get {
                return ResourceManager.GetString("UI_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V1BoardMinimumWidthAcrossLength.
        /// </summary>
        internal static string V1BoardMinimumWidthAcrossLength {
            get {
                return ResourceManager.GetString("V1BoardMinimumWidthAcrossLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MW_V1MaxAllowedMissingWood.
        /// </summary>
        internal static string V1MaxAllowedMissingWood {
            get {
                return ResourceManager.GetString("V1MaxAllowedMissingWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V1MissingChunkMaximumLength.
        /// </summary>
        internal static string V1MissingChunkMaximumLength {
            get {
                return ResourceManager.GetString("V1MissingChunkMaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V1MissingChunkMaximumWidth.
        /// </summary>
        internal static string V1MissingChunkMaximumWidth {
            get {
                return ResourceManager.GetString("V1MissingChunkMaximumWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V2BoardMinimumWidthAcrossLength.
        /// </summary>
        internal static string V2BoardMinimumWidthAcrossLength {
            get {
                return ResourceManager.GetString("V2BoardMinimumWidthAcrossLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MW_V2MaxAllowedMissingWood.
        /// </summary>
        internal static string V2MaxAllowedMissingWood {
            get {
                return ResourceManager.GetString("V2MaxAllowedMissingWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V2MissingChunkMaximumLength.
        /// </summary>
        internal static string V2MissingChunkMaximumLength {
            get {
                return ResourceManager.GetString("V2MissingChunkMaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V2MissingChunkMinimumWidth.
        /// </summary>
        internal static string V2MissingChunkMaximumWidth {
            get {
                return ResourceManager.GetString("V2MissingChunkMaximumWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V3BoardMinimumWidthAcrossLength.
        /// </summary>
        internal static string V3BoardMinimumWidthAcrossLength {
            get {
                return ResourceManager.GetString("V3BoardMinimumWidthAcrossLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MW_V3MaxAllowedMissingWood.
        /// </summary>
        internal static string V3MaxAllowedMissingWood {
            get {
                return ResourceManager.GetString("V3MaxAllowedMissingWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V3MissingChunkMaximumLength.
        /// </summary>
        internal static string V3MissingChunkMaximumLength {
            get {
                return ResourceManager.GetString("V3MissingChunkMaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V3MissingChunkMaximumWidth.
        /// </summary>
        internal static string V3MissingChunkMaximumWidth {
            get {
                return ResourceManager.GetString("V3MissingChunkMaximumWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBoardEdgeCrackExclusionZonePercentage.
        /// </summary>
        internal static string VBoardEdgeCrackExclusionZonePercentage {
            get {
                return ResourceManager.GetString("VBoardEdgeCrackExclusionZonePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBoardLength_in.
        /// </summary>
        internal static string VBoardLength_in {
            get {
                return ResourceManager.GetString("VBoardLength_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBoardWidth_in.
        /// </summary>
        internal static string VBoardWidth_in {
            get {
                return ResourceManager.GetString("VBoardWidth_in", resourceCulture);
            }
        }
    }
}
