//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalletCheck {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringsLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PalletCheck.StringsLocalization", typeof(StringsLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AngleThresholdDegree.
        /// </summary>
        internal static string AngleThresholdDegree {
            get {
                return ResourceManager.GetString("AngleThresholdDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoStartCapturing.
        /// </summary>
        internal static string AutoStartCapturing {
            get {
                return ResourceManager.GetString("AutoStartCapturing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlockHeight1.
        /// </summary>
        internal static string BlockHeight1 {
            get {
                return ResourceManager.GetString("BlockHeight1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlockHeight2.
        /// </summary>
        internal static string BlockHeight2 {
            get {
                return ResourceManager.GetString("BlockHeight2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlockHeight3.
        /// </summary>
        internal static string BlockHeight3 {
            get {
                return ResourceManager.GetString("BlockHeight3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlockWidth1.
        /// </summary>
        internal static string BlockWidth1 {
            get {
                return ResourceManager.GetString("BlockWidth1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlockWidth2.
        /// </summary>
        internal static string BlockWidth2 {
            get {
                return ResourceManager.GetString("BlockWidth2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlockWidth3.
        /// </summary>
        internal static string BlockWidth3 {
            get {
                return ResourceManager.GetString("BlockWidth3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoardCenterCrackExclusionZonePercentage.
        /// </summary>
        internal static string BoardCenterCrackExclusionZonePercentage {
            get {
                return ResourceManager.GetString("BoardCenterCrackExclusionZonePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        internal static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrackTrackerBlockSize.
        /// </summary>
        internal static string CrackTrackerBlockSize {
            get {
                return ResourceManager.GetString("CrackTrackerBlockSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrackTrackerMinDelta.
        /// </summary>
        internal static string CrackTrackerMinDelta {
            get {
                return ResourceManager.GetString("CrackTrackerMinDelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrackTrackerMinPct.
        /// </summary>
        internal static string CrackTrackerMinPct {
            get {
                return ResourceManager.GetString("CrackTrackerMinPct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CropX.
        /// </summary>
        internal static string CropX {
            get {
                return ResourceManager.GetString("CropX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndX0.
        /// </summary>
        internal static string EndX0 {
            get {
                return ResourceManager.GetString("EndX0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndX1.
        /// </summary>
        internal static string EndX1 {
            get {
                return ResourceManager.GetString("EndX1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndX2.
        /// </summary>
        internal static string EndX2 {
            get {
                return ResourceManager.GetString("EndX2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForkClearancePercentage.
        /// </summary>
        internal static string ForkClearancePercentage {
            get {
                return ResourceManager.GetString("ForkClearancePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MW_H1MaxAllowedMissingWood.
        /// </summary>
        internal static string H1MaxAllowedMissingWood {
            get {
                return ResourceManager.GetString("H1MaxAllowedMissingWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_H1MissingChunkMinimumLength.
        /// </summary>
        internal static string H1MissingChunkMinimumLength {
            get {
                return ResourceManager.GetString("H1MissingChunkMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_H1MissingChunkMinimumWidth.
        /// </summary>
        internal static string H1MissingChunkMinimumWidth {
            get {
                return ResourceManager.GetString("H1MissingChunkMinimumWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_H1NarrowBoardMinimumWidth.
        /// </summary>
        internal static string H1NarrowBoardMinimumWidth {
            get {
                return ResourceManager.GetString("H1NarrowBoardMinimumWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MW_H2MaxAllowedMissingWood.
        /// </summary>
        internal static string H2MaxAllowedMissingWood {
            get {
                return ResourceManager.GetString("H2MaxAllowedMissingWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_H2MissingChunkMinimumLength.
        /// </summary>
        internal static string H2MissingChunkMinimumLength {
            get {
                return ResourceManager.GetString("H2MissingChunkMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_H2MissingChunkMinimumWidth.
        /// </summary>
        internal static string H2MissingChunkMinimumWidth {
            get {
                return ResourceManager.GetString("H2MissingChunkMinimumWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_H2NarrowBoardMinimumWidth.
        /// </summary>
        internal static string H2NarrowBoardMinimumWidth {
            get {
                return ResourceManager.GetString("H2NarrowBoardMinimumWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MW_H3MaxAllowedMissingWood.
        /// </summary>
        internal static string H3MaxAllowedMissingWood {
            get {
                return ResourceManager.GetString("H3MaxAllowedMissingWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_H3MissingChunkMinimumLength.
        /// </summary>
        internal static string H3MissingChunkMinimumLength {
            get {
                return ResourceManager.GetString("H3MissingChunkMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_H3MissingChunkMinimumWidth.
        /// </summary>
        internal static string H3MissingChunkMinimumWidth {
            get {
                return ResourceManager.GetString("H3MissingChunkMinimumWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_H3NarrowBoardMinimumWidth.
        /// </summary>
        internal static string H3NarrowBoardMinimumWidth {
            get {
                return ResourceManager.GetString("H3NarrowBoardMinimumWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MW_H4MaxAllowedMissingWood.
        /// </summary>
        internal static string H4MaxAllowedMissingWood {
            get {
                return ResourceManager.GetString("H4MaxAllowedMissingWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_H4MissingChunkMinimumLength.
        /// </summary>
        internal static string H4MissingChunkMinimumLength {
            get {
                return ResourceManager.GetString("H4MissingChunkMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_H4MissingChunkMinimumWidth.
        /// </summary>
        internal static string H4MissingChunkMinimumWidth {
            get {
                return ResourceManager.GetString("H4MissingChunkMinimumWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_H4NarrowBoardMinimumWidth.
        /// </summary>
        internal static string H4NarrowBoardMinimumWidth {
            get {
                return ResourceManager.GetString("H4NarrowBoardMinimumWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MW_H5MaxAllowedMissingWood.
        /// </summary>
        internal static string H5MaxAllowedMissingWood {
            get {
                return ResourceManager.GetString("H5MaxAllowedMissingWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_H5MissingChunkMinimumLength.
        /// </summary>
        internal static string H5MissingChunkMinimumLength {
            get {
                return ResourceManager.GetString("H5MissingChunkMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_H5MissingChunkMinimumWidth.
        /// </summary>
        internal static string H5MissingChunkMinimumWidth {
            get {
                return ResourceManager.GetString("H5MissingChunkMinimumWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_H5NarrowBoardMinimumWidth.
        /// </summary>
        internal static string H5NarrowBoardMinimumWidth {
            get {
                return ResourceManager.GetString("H5NarrowBoardMinimumWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MW_H6MaxAllowedMissingWood.
        /// </summary>
        internal static string H6MaxAllowedMissingWood {
            get {
                return ResourceManager.GetString("H6MaxAllowedMissingWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_H6MissingChunkMinimumLength.
        /// </summary>
        internal static string H6MissingChunkMinimumLength {
            get {
                return ResourceManager.GetString("H6MissingChunkMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_H6MissingChunkMinimumWidth.
        /// </summary>
        internal static string H6MissingChunkMinimumWidth {
            get {
                return ResourceManager.GetString("H6MissingChunkMinimumWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_H6NarrowBoardMinimumWidth.
        /// </summary>
        internal static string H6NarrowBoardMinimumWidth {
            get {
                return ResourceManager.GetString("H6NarrowBoardMinimumWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HBoardEdgeCrackExclusionZonePercentage.
        /// </summary>
        internal static string HBoardEdgeCrackExclusionZonePercentage {
            get {
                return ResourceManager.GetString("HBoardEdgeCrackExclusionZonePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HBoardLength_in.
        /// </summary>
        internal static string HBoardLength_in {
            get {
                return ResourceManager.GetString("HBoardLength_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HBoardWidth_in.
        /// </summary>
        internal static string HBoardWidth_in {
            get {
                return ResourceManager.GetString("HBoardWidth_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_HNarrowBoardMinimumWidthAcrossLenght.
        /// </summary>
        internal static string HNarrowBoardMinimumWidthAcrossLenght {
            get {
                return ResourceManager.GetString("HNarrowBoardMinimumWidthAcrossLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_LeadingBoardMinimumWidthAcrossLength.
        /// </summary>
        internal static string LeadingBoardMinimumWidthAcrossLength {
            get {
                return ResourceManager.GetString("LeadingBoardMinimumWidthAcrossLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MW_LeadingMaxAllowedMissingWood.
        /// </summary>
        internal static string LeadingMaxAllowedMissingWood {
            get {
                return ResourceManager.GetString("LeadingMaxAllowedMissingWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_LeadingMissingChunkMinimumLength.
        /// </summary>
        internal static string LeadingMissingChunkMinimumLength {
            get {
                return ResourceManager.GetString("LeadingMissingChunkMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_LeadingMissingChunkMinimumWidth.
        /// </summary>
        internal static string LeadingMissingChunkMinimumWidth {
            get {
                return ResourceManager.GetString("LeadingMissingChunkMinimumWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_LeadingNarrowBoardMinimumWidth.
        /// </summary>
        internal static string LeadingNarrowBoardMinimumWidth {
            get {
                return ResourceManager.GetString("LeadingNarrowBoardMinimumWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RN_MaxNailHeight_mm.
        /// </summary>
        internal static string MaxNailHeight_mm {
            get {
                return ResourceManager.GetString("MaxNailHeight_mm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiddleBoardMissingWoodMaxPercentage.
        /// </summary>
        internal static string MiddleBoardMissingWoodMaxPercentage {
            get {
                return ResourceManager.GetString("MiddleBoardMissingWoodMaxPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SH_MinBoardLen.
        /// </summary>
        internal static string MinBoardLen {
            get {
                return ResourceManager.GetString("MinBoardLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MissingBlockMinimumRequiredAreaPercentage.
        /// </summary>
        internal static string MissingBlockMinimumRequiredAreaPercentage {
            get {
                return ResourceManager.GetString("MissingBlockMinimumRequiredAreaPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MissingChunkHeightDeviationThreshold.
        /// </summary>
        internal static string MissingChunkHeightDeviationThreshold {
            get {
                return ResourceManager.GetString("MissingChunkHeightDeviationThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMPerPixelX.
        /// </summary>
        internal static string MMPerPixelX {
            get {
                return ResourceManager.GetString("MMPerPixelX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMPerPixelY.
        /// </summary>
        internal static string MMPerPixelY {
            get {
                return ResourceManager.GetString("MMPerPixelY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMPerPixelZ.
        /// </summary>
        internal static string MMPerPixelZ {
            get {
                return ResourceManager.GetString("MMPerPixelZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RN_NailConfirmationsRequired.
        /// </summary>
        internal static string NailConfirmationsRequired {
            get {
                return ResourceManager.GetString("NailConfirmationsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RN_NailConfirmHeadInnerRadius.
        /// </summary>
        internal static string NailConfirmHeadInnerRadius {
            get {
                return ResourceManager.GetString("NailConfirmHeadInnerRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RN_NailConfirmHeadOuterRadius.
        /// </summary>
        internal static string NailConfirmHeadOuterRadius {
            get {
                return ResourceManager.GetString("NailConfirmHeadOuterRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RN_NailConfirmSurfaceRadius.
        /// </summary>
        internal static string NailConfirmSurfaceRadius {
            get {
                return ResourceManager.GetString("NailConfirmSurfaceRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RN_NailNeighborSamplePoints.
        /// </summary>
        internal static string NailNeighborSamplePoints {
            get {
                return ResourceManager.GetString("NailNeighborSamplePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RN_NailNeighborSampleRadius.
        /// </summary>
        internal static string NailNeighborSampleRadius {
            get {
                return ResourceManager.GetString("NailNeighborSampleRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes1.
        /// </summary>
        internal static string Notes1 {
            get {
                return ResourceManager.GetString("Notes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes2.
        /// </summary>
        internal static string Notes2 {
            get {
                return ResourceManager.GetString("Notes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OffsetZ0.
        /// </summary>
        internal static string OffsetZ0 {
            get {
                return ResourceManager.GetString("OffsetZ0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OffsetZ1.
        /// </summary>
        internal static string OffsetZ1 {
            get {
                return ResourceManager.GetString("OffsetZ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OffsetZ2.
        /// </summary>
        internal static string OffsetZ2 {
            get {
                return ResourceManager.GetString("OffsetZ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProtrudingNailHeight.
        /// </summary>
        internal static string ProtrudingNailHeight {
            get {
                return ResourceManager.GetString("ProtrudingNailHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RB_RaisedBoardMaximumHeight.
        /// </summary>
        internal static string RaisedBoardMaximumHeight {
            get {
                return ResourceManager.GetString("RaisedBoardMaximumHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RB_RaisedBoardWidth.
        /// </summary>
        internal static string RaisedBoardWidth {
            get {
                return ResourceManager.GetString("RaisedBoardWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RawCaptureROIBottom_px.
        /// </summary>
        internal static string RawCaptureROIBottom_px {
            get {
                return ResourceManager.GetString("RawCaptureROIBottom_px", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RawCaptureROILeft_px.
        /// </summary>
        internal static string RawCaptureROILeft_px {
            get {
                return ResourceManager.GetString("RawCaptureROILeft_px", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RawCaptureROIMaxZ_px.
        /// </summary>
        internal static string RawCaptureROIMaxZ_px {
            get {
                return ResourceManager.GetString("RawCaptureROIMaxZ_px", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RawCaptureROIMinZ_px.
        /// </summary>
        internal static string RawCaptureROIMinZ_px {
            get {
                return ResourceManager.GetString("RawCaptureROIMinZ_px", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RawCaptureROIRight_px.
        /// </summary>
        internal static string RawCaptureROIRight_px {
            get {
                return ResourceManager.GetString("RawCaptureROIRight_px", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RawCaptureROITop_px.
        /// </summary>
        internal static string RawCaptureROITop_px {
            get {
                return ResourceManager.GetString("RawCaptureROITop_px", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate90.
        /// </summary>
        internal static string Rotate90 {
            get {
                return ResourceManager.GetString("Rotate90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SideLength.
        /// </summary>
        internal static string SideLength {
            get {
                return ResourceManager.GetString("SideLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartX0.
        /// </summary>
        internal static string StartX0 {
            get {
                return ResourceManager.GetString("StartX0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartX1.
        /// </summary>
        internal static string StartX1 {
            get {
                return ResourceManager.GetString("StartX1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartX2.
        /// </summary>
        internal static string StartX2 {
            get {
                return ResourceManager.GetString("StartX2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        internal static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TopH{0}BoardWidth_in.
        /// </summary>
        internal static string TopHXBoardWidth_in {
            get {
                return ResourceManager.GetString("TopHXBoardWidth_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MW_TrailingMaxAllowedMissingWood.
        /// </summary>
        internal static string TrailingMaxAllowedMissingWood {
            get {
                return ResourceManager.GetString("TrailingMaxAllowedMissingWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_TrailingMissingChunkMinimumLength.
        /// </summary>
        internal static string TrailingMissingChunkMinimumLength {
            get {
                return ResourceManager.GetString("TrailingMissingChunkMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_TrailingMissingChunkMinimumWidth.
        /// </summary>
        internal static string TrailingMissingChunkMinimumWidth {
            get {
                return ResourceManager.GetString("TrailingMissingChunkMinimumWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_TrailingNarrowBoardMinimumWidth.
        /// </summary>
        internal static string TrailingNarrowBoardMinimumWidth {
            get {
                return ResourceManager.GetString("TrailingNarrowBoardMinimumWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallet Check POC.
        /// </summary>
        internal static string UI_Title {
            get {
                return ResourceManager.GetString("UI_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MW_V1MaxAllowedMissingWood.
        /// </summary>
        internal static string V1MaxAllowedMissingWood {
            get {
                return ResourceManager.GetString("V1MaxAllowedMissingWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_V1MissingChunkMinimumLength.
        /// </summary>
        internal static string V1MissingChunkMinimumLength {
            get {
                return ResourceManager.GetString("V1MissingChunkMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_V1MissingChunkMinimumWidth.
        /// </summary>
        internal static string V1MissingChunkMinimumWidth {
            get {
                return ResourceManager.GetString("V1MissingChunkMinimumWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_V1NarrowBoardMinimumWidth.
        /// </summary>
        internal static string V1NarrowBoardMinimumWidth {
            get {
                return ResourceManager.GetString("V1NarrowBoardMinimumWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MW_V2MaxAllowedMissingWood.
        /// </summary>
        internal static string V2MaxAllowedMissingWood {
            get {
                return ResourceManager.GetString("V2MaxAllowedMissingWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_V2MissingChunkMinimumLength.
        /// </summary>
        internal static string V2MissingChunkMinimumLength {
            get {
                return ResourceManager.GetString("V2MissingChunkMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_V2MissingChunkMinimumWidth.
        /// </summary>
        internal static string V2MissingChunkMinimumWidth {
            get {
                return ResourceManager.GetString("V2MissingChunkMinimumWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_V2NarrowBoardMinimumWidth.
        /// </summary>
        internal static string V2NarrowBoardMinimumWidth {
            get {
                return ResourceManager.GetString("V2NarrowBoardMinimumWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MW_V3MaxAllowedMissingWood.
        /// </summary>
        internal static string V3MaxAllowedMissingWood {
            get {
                return ResourceManager.GetString("V3MaxAllowedMissingWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_V3MissingChunkMinimumLength.
        /// </summary>
        internal static string V3MissingChunkMinimumLength {
            get {
                return ResourceManager.GetString("V3MissingChunkMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_V3MissingChunkMinimumWidth.
        /// </summary>
        internal static string V3MissingChunkMinimumWidth {
            get {
                return ResourceManager.GetString("V3MissingChunkMinimumWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BN_V3NarrowBoardMinimumWidth.
        /// </summary>
        internal static string V3NarrowBoardMinimumWidth {
            get {
                return ResourceManager.GetString("V3NarrowBoardMinimumWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBoardEdgeCrackExclusionZonePercentage.
        /// </summary>
        internal static string VBoardEdgeCrackExclusionZonePercentage {
            get {
                return ResourceManager.GetString("VBoardEdgeCrackExclusionZonePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBoardLength_in.
        /// </summary>
        internal static string VBoardLength_in {
            get {
                return ResourceManager.GetString("VBoardLength_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBoardWidth_in.
        /// </summary>
        internal static string VBoardWidth_in {
            get {
                return ResourceManager.GetString("VBoardWidth_in", resourceCulture);
            }
        }
    }
}
